# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Mygit/PCC-HomeWork/6. R-I_Instructions/R-I_Instructions.srcs/sources_1/ip/Data_ROM/Data_ROM.xci
# IP: The module: 'Data_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mygit/PCC-HomeWork/6. R-I_Instructions/R-I_Instructions.srcs/sources_1/ip/Data_ROM/Data_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Mygit/PCC-HomeWork/6. R-I_Instructions/R-I_Instructions.srcs/sources_1/ip/Data_ROM/Data_ROM.xci
# IP: The module: 'Data_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mygit/PCC-HomeWork/6. R-I_Instructions/R-I_Instructions.srcs/sources_1/ip/Data_ROM/Data_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
